version: 2

sphinx:
  configuration: doc/source/conf.py
  fail_on_warning: true

python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - requirements: doc/requirements.txt
    - method: pip
      path: .
