name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    name: unit test [python-${{ matrix.python-version }}]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          conda install -y -c conda-forge --file tests/requirements.txt

      - name: Build
        run: |
          python -m pip install -e .

      - name: Run tests
        run: |
          cd ..
          python -m unittest discover -s relentless -v
