name: test

on:
  pull_request:

  push:
    branches:
      - main

  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: unit test [python-${{ matrix.python-version }}]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            tests/requirements.txt

      - name: Install
        run: |
          python -m pip install pip --upgrade pip
          pip install -r tests/requirements.txt
          pip install .

      - name: Test
        run: |
          cd ..
          python -m unittest discover -v -s ./relentless/tests -p 'test_*.py'
